name: zshgpt
summary: Power up your zsh with gpt
description: Power up your zsh with gpt.
grade: stable
confinement: strict
base: core22
adopt-info: zshgpt
architectures:
  - build-on: [arm64, armhf, amd64]

apps:
  zshgpt:
    command: bin/zshgpt
    plugs: [home, network, network-bind, removable-media]

parts:
  zshgpt:
    plugin: python
    python-packages: [zshgpt]
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0 | cut -c 2-)
